/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trab.h"

bool_t
xdr_commomattributtes (XDR *xdrs, commomattributtes *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->address, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->booleanVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_control (XDR *xdrs, control *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_commomattributes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_form (XDR *xdrs, form *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_int (xdrs, &objp->ask_id))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->ask, 140,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->options, 140,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 + ( 3 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->answer, 3,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->next))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->answer;
				i < 3; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		IXDR_PUT_LONG(buf, objp->next);
		}
		 if (!xdr_commomattributes (xdrs, &objp->attr))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_int (xdrs, &objp->ask_id))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->ask, 140,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->options, 140,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 + ( 3 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->answer, 3,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->next))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->answer;
				i < 3; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		objp->next = IXDR_GET_LONG(buf);
		}
		 if (!xdr_commomattributes (xdrs, &objp->attr))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->ask_id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ask, 140,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->options, 140,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->answer, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->next))
		 return FALSE;
	 if (!xdr_commomattributes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_infoperson (XDR *xdrs, infoperson *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->age))
		 return FALSE;
	 if (!xdr_commomattributes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}
