/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trab.h"

control *
whatdoto_1_svc(control *argp, struct svc_req *rqstp)
{
	static control  result;

	/*
	 * insert server code here
	 */

	return &result;
}

control *
checkhost_1_svc(control *argp, struct svc_req *rqstp)
{
	static control  result;

	/*
	 * insert server code here
	 */

	return &result;
}

form *
sendask_1_svc(form *argp, struct svc_req *rqstp)
{
	static form  result;

	/*
	 * insert server code here
	 */

	return &result;
}

form *
sendanswer_1_svc(form *argp, struct svc_req *rqstp)
{
	static form  result;

	/*
	 * insert server code here
	 */

	return &result;
}

infoperson *
nicetomeetyou_1_svc(infoperson *argp, struct svc_req *rqstp)
{
	static infoperson  result;

	/*
	 * insert server code here
	 */

	return &result;
}
