/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "trab.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

control *
whatdoto_1(control *argp, CLIENT *clnt)
{
	static control clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, whatdoto,
		(xdrproc_t) xdr_control, (caddr_t) argp,
		(xdrproc_t) xdr_control, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

control *
checkhost_1(control *argp, CLIENT *clnt)
{
	static control clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, checkhost,
		(xdrproc_t) xdr_control, (caddr_t) argp,
		(xdrproc_t) xdr_control, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

form *
sendask_1(form *argp, CLIENT *clnt)
{
	static form clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sendask,
		(xdrproc_t) xdr_form, (caddr_t) argp,
		(xdrproc_t) xdr_form, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

form *
sendanswer_1(form *argp, CLIENT *clnt)
{
	static form clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sendanswer,
		(xdrproc_t) xdr_form, (caddr_t) argp,
		(xdrproc_t) xdr_form, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

infoperson *
nicetomeetyou_1(infoperson *argp, CLIENT *clnt)
{
	static infoperson clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, nicetomeetyou,
		(xdrproc_t) xdr_infoperson, (caddr_t) argp,
		(xdrproc_t) xdr_infoperson, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
