/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trab.h"

bool_t
xdr_commomattributtes (XDR *xdrs, commomattributtes *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->address, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->booleanVar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_control (XDR *xdrs, control *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_commomattributtes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_form (XDR *xdrs, form *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->ask_id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ask, 140,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->options, 140,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->answer))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->next))
		 return FALSE;
	 if (!xdr_commomattributtes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_infoperson (XDR *xdrs, infoperson *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->age))
		 return FALSE;
	 if (!xdr_commomattributtes (xdrs, &objp->attr))
		 return FALSE;
	return TRUE;
}
