/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRAB_H_RPCGEN
#define _TRAB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct commomattributtes {
	char address[40];
	int booleanVar;
};
typedef struct commomattributtes commomattributtes;

struct control {
	int action;
	commomattributtes attr;
};
typedef struct control control;

struct form {
	int ask_id;
	char ask[140];
	char options[140];
	int answer[3];
	int next;
	commomattributtes attr;
};
typedef struct form form;

struct infoperson {
	char name[40];
	int age;
	commomattributtes attr;
};
typedef struct infoperson infoperson;

#define PROGJOGO 0x10232143
#define VERJOGO 1


extern current_user;
#if defined(__STDC__) || defined(__cplusplus)
#define whatdoto 1
extern  control * whatdoto_1(control *, CLIENT *);
extern  control * whatdoto_1_svc(control *, struct svc_req *);
#define checkhost 2
extern  control * checkhost_1(control *, CLIENT *);
extern  control * checkhost_1_svc(control *, struct svc_req *);
#define sendask 3
extern  form * sendask_1(form *, CLIENT *);
extern  form * sendask_1_svc(form *, struct svc_req *);
#define sendanswer 4
extern  form * sendanswer_1(form *, CLIENT *);
extern  form * sendanswer_1_svc(form *, struct svc_req *);
#define nicetomeetyou 5
extern  infoperson * nicetomeetyou_1(infoperson *, CLIENT *);
extern  infoperson * nicetomeetyou_1_svc(infoperson *, struct svc_req *);
extern int progjogo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define whatdoto 1
extern  control * whatdoto_1();
extern  control * whatdoto_1_svc();
#define checkhost 2
extern  control * checkhost_1();
extern  control * checkhost_1_svc();
#define sendask 3
extern  form * sendask_1();
extern  form * sendask_1_svc();
#define sendanswer 4
extern  form * sendanswer_1();
extern  form * sendanswer_1_svc();
#define nicetomeetyou 5
extern  infoperson * nicetomeetyou_1();
extern  infoperson * nicetomeetyou_1_svc();
extern int progjogo_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_commomattributtes (XDR *, commomattributtes*);
extern  bool_t xdr_control (XDR *, control*);
extern  bool_t xdr_form (XDR *, form*);
extern  bool_t xdr_infoperson (XDR *, infoperson*);

#else /* K&R C */
extern bool_t xdr_commomattributtes ();
extern bool_t xdr_control ();
extern bool_t xdr_form ();
extern bool_t xdr_infoperson ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRAB_H_RPCGEN */
